### ISSUE TITLE
Unable to Install Themes and Extensions 

### ISSUE THREAD

**Issue by JaidenIsDum** [spicetify/spicetify-marketplace#169]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Latest 
- Spicetify version: Latest
```

### 📝 Description

Hovering over ui does not bring the install icon prompt 

Manually installing themes work but the theme I am using **comfy** is now how it used to look like! 

### 📸 Screenshots

<img width="265" alt="image" src="https://user-images.githubusercontent.com/104072495/164220758-a3d896b7-e261-4f88-a048-b58043c160d6.png">

**Comment by CharlieS1103** [comment]
@JaidenIsDum Which theme do you have installed

**Comment by CharlieS1103** [comment]
@JaidenIsDum try uninstalling all themes you have installed to see if it is an issue with marketplace or just an issue with themes (most definitely an issue with themes.)

**Comment by GalxFieri** [comment]
Im having the same black screen issue with spotify since their latest update. Using Spotify Spotify for Windows
1.1.83.956.gbe7ea9a7 from their website directly. 

Tried uninstalling spotify, removing all spicetify folders, rebooted, reinstalled spotify, tried installing the marketplace again and still receiving a black spotify after "all spicetified up" on powershell (as admin)

**Comment by CharlieS1103** [comment]
@GalxFieri That is a spicetify issue which as been resolved. Run ``spicetify upgrade``
