### ISSUE TITLE
Optimize or better handle API limits

### ISSUE THREAD

**Issue by theRealPadster** [spicetify/spicetify-marketplace#33]
When switching back and forth between the marketplace and installed tabs, it makes a LOT of API calls (since we have one per page and then another one per extension in the results). This results in the API limit being hit and the calls to 403 error, which breaks stuff. 

We should see if there is a way to fetch what we need without gobbling up API calls like it's pumpkin pie on Thanksgiving. And if that's not possible, at least have a more graceful fallback than just being stuck indefinitely with a loading icon.

**Comment by CharlieS1103** [comment]
- Do our initial fetch of the github repos with the tag in extension.js
-  Filter out the incorrect ones and save all the correct extensions along with their info to an array in local storage(or something of that sort)
- Do the same to themes(we do this keeping in account githubs rate limiting)
-  Continue doing this in the background until we've cached every correct one

**Comment by theRealPadster** [comment]
We'd also want some value saved for when things were last cached, so it knows when the data is stale and it should query again and recache.

**Comment by CharlieS1103** [comment]
@theRealPadster started working on this in the optimization branch, I believe I've figured out how to do it, but one concern I harbor is that if we reach the API limit before the user clicks marketplace, it would take even longer to load (would probably only load the ones that have already been cached)

**Comment by theRealPadster** [comment]
> @theRealPadster started working on this in the optimization branch, I believe I've figured out how to do it, but one concern I harbor is that if we reach the API limit before the user clicks marketplace, it would take even longer to load (would probably only load the ones that have already been cached)

Can you throttle it? e.g. wait 200ms between loading them or something?

**Comment by CharlieS1103** [comment]
@theRealPadster Finished the first few steps: Next steps are to cache the information fetched by getThemeRepos and getRepos functions. After doing that, we can use that info instead of fetching them in index.js. We can also then remove themes/extensions from the cached getThemeRepos and getRepos that do not have a manifest (thus speeding up the loading process drastically.) If there's anything you'd like further elaboration on feel free to ask, this explanation probably isn't the greatest as it's  1:12 am for me

**Comment by CharlieS1103** [comment]
@theRealPadster 

Pretty much i fetch all the extension reos and all the themes repos
Filter out blacklisted ones
Then loop thotugh fetching each manifest
If the manifest fails to fetch it’ll append the url to an array in local storage
And if it fetches properly it’ll make a key with the repo name and user for a name with the manifest as a value
Then in index.js, in the getRepoManifest function
It’ll check if the repo name + repo user key exists within session storage
If it does it will return that value instead of fetching another manifest
Then if it doesn't, it'll check if the url exists in the array of failures
and if it does it'll just return null instead of trying to fetch
ultimately what this does is removes the need for it to fetch anything entirely, this speeding up the process significantly and more or less removing rate limit concerns (over time)

**Comment by CharlieS1103** [comment]
@theRealPadster Currently the main issue i'm having is that for certain repos it'll load twice, not really sure why. I haven't attempted fixing it in a while (tried like 6 different methods a week ago and haven't had time nor energy to try again yet.)

**Comment by theRealPadster** [comment]
@CharlieS1103 Can this be closed?

**Comment by CharlieS1103** [comment]
@theRealPadster Yup!

**Comment by bluelhf** [comment]
There seems to still be issues with this in some cases — Perhaps a better solution would be to cache these results on a back-end server that makes authenticated requests instead? If the maintenance costs for this are too high, an OAuth2 flow could be implemented to allow users to authenticate requests with GitHub for increased rate limits. Or, in the least, the error should report the next possible request time sent by the GitHub API when the rate limit is reached, so the user is aware of when it's okay to open the tab again.

![Current behaviour](https://user-images.githubusercontent.com/52505120/203041471-28c2d656-270e-4c60-9ea5-15d91d85e27f.png)

**Comment by CharlieS1103** [comment]
Going to assume this is just an issue with your network, you'd theoretically have to switch tabs 20 times in one minute in order to get the too many requests error.
