### ISSUE TITLE
Automatic color scheme switching according to OS light/dark mode

### ISSUE THREAD

**Issue by r0uv3n** [spicetify/spicetify-marketplace#398]
### 📝 Provide a description of the new feature

Windows has a setting to switch between light and dark mode (this may for example be automated to happen with sunset/sunrise).  It would be nice if it would be possible for Spicetify to switch color scheme (and maybe even the whole theme) according to this setting.

Alternatively, it would be great if switching the color scheme via CLI could be made possibly, such that one could use scripts to change color schemes. Right now, changing the color scheme or the theme of spicetify (while spicetify-marketplace is loaded) is only possible via the marketplace interface itself, as far as I know.

**Comment by theRealPadster** [comment]
1. The spotify app forces the OS dark theme and we can't detect it. 
2. You can use the cli to change colour schemes, but because of the way marketplace works, it overrides local theme. We can not change this. If you'd like to automate it, you'll have to either use a local theme, or use an extension to automatically change the marketplace colour scheme
