### ISSUE TITLE
Rename denied 

### ISSUE THREAD

**Issue by KnightKing2179** [spicetify/spicetify-marketplace#405]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for Windows
1.2.0.1165.gabf054ab
- Spicetify version: v2.14.3
```

### 📝 Description

![Screenshot (123)](https://user-images.githubusercontent.com/92685947/207756380-a90896b1-aeb6-42d8-9fd0-bb68535d399d.png)

**Comment by kyrie25** [comment]
After doing further research it has been indicated that there is some process or app that has locked file access as the error displayed.
This is not because of any path malformation because all other processes has ran successfully (downloading & extracting the zip file)

https://social.technet.microsoft.com/Forums/windows/en-US/8ff20c90-2fcf-4fe4-ae08-eecbf9168b91/powershell-renameitem-returning-quotaccess-to-the-path-pathname-is-deniedquot?forum=winserverpowershell

Try removing everything under `%appdata%/spicetify`, upgrade Powershell and run the install script again.
Or install Marketplace manually via the wiki.

**Comment by KnightKing2179** [comment]
> After doing further research it has shown that there is some process or app that has locked file access as the error displayed. This is not because of any path malformation because all other commands ran successfully (downloading & extracting the zip file)
> 
> https://social.technet.microsoft.com/Forums/windows/en-US/8ff20c90-2fcf-4fe4-ae08-eecbf9168b91/powershell-renameitem-returning-quotaccess-to-the-path-pathname-is-deniedquot?forum=winserverpowershell
> 
> Try removing everything under `%appdata%/spicetify`, upgrade Powershell and run the install script again. Antivirus programs may cause the problem also. You can also install Marketplace manually via the wiki.

thx
