### ISSUE TITLE
Search by developer does't work as intended

### ISSUE THREAD

**Issue by Tetrax-10** [spicetify/spicetify-marketplace#452]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
Spotify for Windows
1.2.7.1275.g586348e7
Spicetify vDev
```

### 📝 Description

-

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/75513645/224544885-3a7b295b-cfde-471d-89e5-3db54c9e7cde.png)

## Copy to Clipboard is also developed by me and the card says Tetrax-10

![image](https://user-images.githubusercontent.com/75513645/224545070-9bf9ebf2-4160-4f39-b479-6a2e50503b6a.png)

**Comment by theRealPadster** [comment]
The search function passes the query to the search GitHub API. I'm guessing it doesn't show up when you search tetrax because the repo doesn't have your name on it and you are not the owner, so the result doesn't show up. Not something we can control. I didn't even realize that you _could_ search by developer until now.

**Comment by Tetrax-10** [comment]
Got fixed, thx.

but if i press enter everything goes off

![image](https://user-images.githubusercontent.com/75513645/224611890-1a478649-a89f-49a5-a9bf-98db76459d2c.png)

**Comment by kyrie25** [comment]
> Got fixed, thx.
> 
> 
> 
> but if i press enter everything goes off

API queries will be removed in future patches
