### ISSUE TITLE
[Marketplace] Add an "Update extensions" button

### ISSUE THREAD

**Issue by fr3nchalp4a** [spicetify/spicetify-marketplace#599]
### 📝 Provide a description of the new feature

Permit the user to update all of his extensions, themes, apps and snippets installed via the marketplace :
- remove every extensions/themes/snippets/apps
- remove every source files (except preferences)
- re-download everything
- and finally apply and reload

I don't know how the marketplace handles all this, but it could remember the `github.com/USER/REPO` address, and then re-download the manifest file to get the latest version.

### ➕ Additional Information

A little button in the marketplace, maybe even a service that checks in the background everything installed, fetches the manifest, and check if updates are needed. If it is the case, a button in the top-left corner (like Spicetify updates) asks the user to update everything. If there is nothing to update, still allow the user to manually re-download everything by the button in the Marketplace page.

![Capture d’écran du 2023-09-18 19-20-46](https://github.com/spicetify/spicetify-cli/assets/68474172/764721dc-931a-4917-832b-b61083883e1a)
![Capture d’écran du 2023-09-18 19-33-10](https://github.com/spicetify/spicetify-cli/assets/68474172/7a6c2bec-f4f2-4268-a12a-06d4498c6e5b)

**Comment by rxri** [comment]
Marketplace injects extensions/custom apps/themes with script tag which is using [jsdelivr.com](https://www.jsdelivr.com/) cdn. This button wouldn't make such sense since cache is on CDN end and there's not much we can do. The simple spotify restart (CTRL+R) should load the latest version available in cdn

**Comment by rxri** [comment]
Basically, we do not provide any API in spicetify to work with file system. Spotify have it disabled too. There was some conversation about saving this stuff in localStorage, however it's limited in size (5MB iirc), and that wouldn't allow on much since it's shared and other extensions/custom apps use it as well

**Comment by CharlieS1103** [comment]
It might be relatively simple but poses a lot of security issues. Also might be complex, either way not the best idea.

**Comment by fr3nchalp4a** [comment]
Ok, thanks for answering my (very) noob questions 😂 !
