### ISSUE TITLE
Add Download Count to Marketplace Listings

### ISSUE THREAD

**Issue by Fl3xm3ist3r** [spicetify/spicetify-marketplace#607]
### 📝 Provide a description of the new feature

I propose one enhancement for Spicetify Marketplace:

1.  Download Count Display:

> Show download counts for extensions to highlight their popularity and community trust.

Benefits:

Informed Choices: 

> Users can easily identify trusted and popular extensions, making informed decisions for their projects.

Community Trust: 

> Download counts act as social proof, boosting trust among users and encouraging wider adoption.

**Comment by surfbryce** [comment]
@Fl3xm3ist3r You already closed this so I'm assuming you found something else and I just saw this in the Spicetify discord in the github-updates channel but your first bullet point is literally impossible.

Spicetify uses a CDN so first off there is no direct download from GitHub. Secondly, it's not a download in the first place anyways since we're just referencing a single file by URL (if we simplify the whole process).

You also used to have a second bullet point for sorting options which are already planned to be implemented/being worked on.

**Comment by Fl3xm3ist3r** [comment]
@surfbryce Yeah, I found out that you already sort the extensions after the amount of GitHub stars. So my initial request was kinda redundant.

Thanks for the explanation, and sorry for the trouble. I'm still kinda new into coding… 😅

**Comment by surfbryce** [comment]
@Fl3xm3ist3r No problem, I don't work on the project at all. I just know how it works so just wanted to give the explanation to ya! Good luck on the rest of your coding!
