### ISSUE TITLE
Manual uninstall of a theme

### ISSUE THREAD

**Issue by tsuliwaensis** [spicetify/spicetify-marketplace#712]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.33.1042.g26c92729
- Spicetify version: 2.36.0
```

### 📝 Description

I installed a theme and it made Spotify completely useless (see screenshot). I am unable to go to the Marketplace with the applied theme and remove it. I caan restore Spotify, but no matter what I try the broken theme comes back when I try to do anything with Spicetify

### 📸 Screenshots

![Screenshot 2024-03-27 at 10 32 47 PM](https://github.com/spicetify/spicetify-marketplace/assets/40817465/bb7bd4e0-ffd1-4faf-a504-758ea6a8fa4d)

**Comment by theRealPadster** [comment]
Looked like you installed it locally, which overrides marketplace. Remove the theme locally(from your config file) and its extension, because dribbblish.js breaks stuff if you're not using it.

**Comment by tsuliwaensis** [comment]
My Spicetify config file doesn't list Dribble as the theme. It has `current_theme = marketplace`. I can't find any references to Dribble

**Comment by theRealPadster** [comment]
Does it have the extension installed in the `[extensions]` section?

**Comment by tsuliwaensis** [comment]
I don't have an `[extensions]` section.

Here is my config file

````[AdditionalOptions]
custom_apps           = marketplace
sidebar_config        = 0
home_config           = 1
experimental_features = 0
extensions            = 

[Patch]

[Setting]
prefs_path             = /Users/tsuliwaensis/Library/Application Support/Spotify/prefs
inject_theme_js        = 1
inject_css             = 1
overwrite_assets       = 1
spotify_launch_flags   = 
check_spicetify_update = 1
spotify_path           = /Applications/Spotify.app/Contents/Resources
current_theme          = marketplace
color_scheme           = 
replace_colors         = 1
always_enable_devtools = 0

[Preprocesses]
expose_apis        = 1
disable_sentry     = 1
disable_ui_logging = 1
remove_rtl_rule    = 1

; DO NOT CHANGE!
[Backup]
version = 
with    = ````

**Comment by theRealPadster** [comment]
You could try resetting marketplace?

**Comment by tsuliwaensis** [comment]
> You could try resetting marketplace?

How do I go about doing that? I don't see it in the docs

**Comment by DankestFke** [comment]
extensions and themes doesn't show in normal file location path when installed with marketplace, 
![image](https://github.com/spicetify/spicetify-marketplace/assets/62785913/077b37d9-d059-4e50-8cb0-5d4ba0b01a1e)
as you can see i have downloaded two extensions for spicetify with marketplace but it doesnt shows in /CustomApps folder neither inside the /marketplace customaps folder
![image](https://github.com/spicetify/spicetify-marketplace/assets/62785913/ed34e87c-aee0-45cb-bc70-311514b50820)
![image](https://github.com/spicetify/spicetify-marketplace/assets/62785913/26504539-1bf9-45e1-89cf-cc1113724c85)

I think the problem is the marketplace, it doesn't have any specific location shown, at the same time its not listed in xpui config too
`[Setting]
inject_css             = 1
replace_colors         = 1
overwrite_assets       = 0
spotify_launch_flags   = 
spotify_path           = C:\Users\Syah\AppData\Roaming\Spotify
prefs_path             = C:\Users\Syah\AppData\Roaming\Spotify\prefs
inject_theme_js        = 1
always_enable_devtools = 0
current_theme          = marketplace
color_scheme           = dark
check_spicetify_update = 1

[Preprocesses]
disable_sentry     = 1
disable_ui_logging = 1
remove_rtl_rule    = 1
expose_apis        = 1

[AdditionalOptions]
extensions            = 
custom_apps           = marketplace|lyrics_plus|stats
sidebar_config        = 1
home_config           = 1
experimental_features = 1

[Patch]
xpui.js_find_8008 = .(\w+=)32,
xpui.js_repl_8008 = ,${1}56,

; DO NOT CHANGE!
[Backup]
version = 1.2.37.701.ge66eb7bc
with    = 2.36.11
`

**Comment by theRealPadster** [comment]
@DankestFke the marketplace does not store files locally. It loads them dynamically like a web page does.
