### ISSUE TITLE
Snippets show undefined star count

### ISSUE THREAD

**Issue by theRealPadster** [spicetify/spicetify-marketplace#82]
**Describe the bug**
The cards on the snippets tab show "undefined" as the star count when enabled. We should just hide the star count. 

**Screenshots**
![image](https://user-images.githubusercontent.com/1565883/146940636-4dcd8888-8ce6-4631-9ddc-2518f8bb1e88.png)

**Comment by CharlieS1103** [comment]
@theRealPadster Instead of making it not display at all, should we just migrate stars to an internal feature?
Some ways we could do this:
Use google sheets web API(Pros: Very little rate limit, would most likely never become an issue) Cons: It's google sheets, so the fetching of data would probably be finicky and time-consuming unless we were to create an organizational system to expedite the process
Use  firebase: Pros: Allows for queries(Not sure if google sheets has this as well, but this certainly seems easier), more organized and manageable than google sheets. Cons: Lower rate limit, would hardly be a problem at the current stage in marketplace.

**Comment by CharlieS1103** [comment]
For refererence: https://console.firebase.google.com/u/0/project/spicetify-marketplace/usage
https://developers.google.com/sheets/api/reference/limits#:~:text=This%20version%20of%20the%20Google,is%20no%20daily%20usage%20limit.

**Comment by theRealPadster** [comment]
Yeah stars should probably be internal. They both don't look super scalable in the long run, tbh. And we'd definitely need to implement caching if we don't want to use up all the quotas super fast. e.g. loading extensions tab would be 14 each time a single user loads that tab (or once if we group all stars as one endpoint).

**Comment by theRealPadster** [comment]
I'm gonna close this cause we hid the star count for snippets ages ago.
